default_settings: null
behaviors:
  MazeCleaner:
    trainer_type: sac
    hyperparameters:
      batch_size: 128
      buffer_size: 1000000
      learning_rate: 0.0003
      learning_rate_schedule: linear
      buffer_init_steps: 5000
      tau: 0.005
      init_entcoef: 0.25
    network_settings:
      hidden_units: 64
      num_layers: 2
      vis_encode_type: simple
      memory_size: 64
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 250000
    max_steps: 500000
    time_horizon: 500
    summary_freq: 50000
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  num_areas: 1
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20.0
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: null
checkpoint_settings:
  load_model: false
  results_dir: results
torch_settings:
  device: null
debug: false
